typography_spectrum: 0.012579003814607859
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.830573518993333
  lightness: 0.11576797906309366
  saturation: 0.2582304673269391
  rhythmicContrast: 0.8193656546063721
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49074315652251244
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a70c6a70-8f9e-46a6-9ef8-89c26719e20f.png
name: Draft Production Site
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Experience Refresh
purpose: []
