name: Draft Production Site
favicon: null
layout_spectrum: 0.49074315652251244
typography_spectrum: 0.012579003814607859
title: Onboarding Analytics Environment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.830573518993333
  lightness: 0.11576797906309366
  saturation: 0.2582304673269391
  rhythmicContrast: 0.8193656546063721
purpose: []
